font_family      JetBrains Mono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13.0

cursor_trail 0
mouse_hide_wait -1.0
confirm_os_window_close 0
cursor none

background #08090f
background_opacity 1.0
dynamic_background_opacity yes

disable_ligatures always
hide_window_decorations no
tab_bar_style powerline

scrollback_lines 2000
scrollbar scrolled

sync_to_monitor yes
input_delay 0

tab_bar_edge top
tab_powerline_style round
inactive_tab_foreground #f3f3e7
inactive_tab_background #890149
active_tab_background   #f7e7ce
active_tab_foreground   #3c1a4f
active_tab_font_style   bold-italic
inactive_tab_font_style normal

# Use fish shell
shell fish

# Copy
map ctrl+c    copy_or_interrupt

# Search
map ctrl+k scroll_line_up
map ctrl+j scroll_line_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+kp_add  change_font_size all +1
map ctrl+minus       change_font_size all -1
map ctrl+underscore       change_font_size all -1
map ctrl+0 change_font_size all 0
map ctrl+shift+1 set_background_opacity 1.0
map ctrl+shift+0 set_background_opacity 0.75
