search_limit: 25
default_download_path: ~/Videos
spotify_download_path: ~/Music
default_quality: best
sort_by_default: relevance
embed_subtitles: false
embed_metadata: true
embed_chapters: true
embed_thumbnail: false
ffmpeg_path: ""
yt_dlp_path: ""
video_format: mp4
audio_format: mp3
cookies_browser: ""
cookies_file: ""
thumbnail_preview: true
thumbnail_timeout_ms: 2500
thumbnail_protocol: ""
thumbnail_quality: max
list_compact_mode: false
js_runtime: ""
js_runtime_path: ""
player: mpv
background_playback: false
