monitor = , preferred , auto, 1

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = ELECTRON_OZONE_PlATFORM_HINT,auto

source=config/keymaps.conf
source=config/animations.conf
source=config/general.conf
source=config/rules.conf

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

exec-once = prime-run qs
exec-once = hyprpaper
