input {
		kb_layout = de,ua
        kb_variant = qwerty, 
		kb_model =
		kb_options = grp:win_space_toggle
		kb_rules =
		numlock_by_default = false
		repeat_delay = 200
		repeat_rate = 30

		follow_mouse = 1


		touchpad {
			natural_scroll = false
		}
}
