general {
    gaps_in = 4
    gaps_out = 5

    border_size = 3

    col.active_border = rgba(ffdd00ff) rgba(ffc300ff) 45deg
    col.inactive_border = rgba(595959aa)

    resize_on_border = false

    allow_tearing = false

    no_focus_fallback = true

}

decoration {
    rounding = 18
    rounding_power = 2 

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = false
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}


dwindle {
}

master {
    new_status = master
}

misc {
}



input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    repeat_delay = 200
    repeat_rate = 30

    follow_mouse = 1


    touchpad {
        natural_scroll = false
    }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
