input {
	kb_layout = us
		kb_variant =
#	kb_layout = de,ua
#	kb_variant = qwerty, 
		kb_model =
		kb_options = grp:win_space_toggle
		kb_rules =
		numlock_by_default = false
		repeat_delay = 200
		repeat_rate = 30

		follow_mouse = 1


		touchpad {
			natural_scroll = false
		}
}
general {
    gaps_in = 0
    gaps_out = 0

    border_size = 0

    col.active_border = rgba(ffffffff) rgba(ffffffff) 180deg
    # col.inactive_border = rgba(000000ff)

    resize_on_border = false

    allow_tearing = true

    no_focus_fallback = true

}

decoration {
    rounding = 0 
    rounding_power = 0 

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}


dwindle {
  preserve_split = true
  smart_split = false
  smart_resizing = true
}

master {
    new_status = master
}


misc {
  vrr = 1
  disable_hyprland_logo = true
  disable_splash_rendering = true
  force_default_wallpaper = 0
}

binds {
  scroll_event_delay = 0
  hide_special_on_workspace_change = true
}

xwayland {
  force_zero_scaling = true
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
