set-option -g default-terminal "screen-256color"
set -g base-index 1
set -g pane-base-index 1
setw -g mode-keys vi
set -g status-keys vi
set -g history-limit 4096

set -g pane-border-fg black
set -g pane-active-border-fg brightred

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -r J resize-pane -D 3
bind-key -r K resize-pane -U 3
bind-key -r H resize-pane -L 3
bind-key -r L resize-pane -R 3
bind p paste-buffer
bind : command-prompt
